### ISSUE TITLE
Support KM per hour

### ISSUE THREAD

**Issue by TheWizard1328** [j-vanetten/openpilot#2]
**Is your feature request related to a problem? Please describe.**

I love the work you've done with your fork. 
But as I live in Canada it would be nice to have the ACC+/- buttons and any other areas where settings are Mile per hour set to work, show and set in Kmph if OP settings are set to metric.

**Comment by j-vanetten** [comment]
When jvePilot's metric is enabled

* ACC Minimum is 30 KPH
* ACC +/- changes by 5 instead of 8

Setting in the UI that are in MPH will remain in MPH as the work needed isn't worth the effort.  Users who dive into the settings can do simple math to do the conversion.

**Comment by j-vanetten** [comment]
Feature Merged
