### ISSUE TITLE
Can't install j-vanetten open pilot on my C2

### ISSUE THREAD

**Issue by iamphildeez** [j-vanetten/openpilot#25]
**Describe the bug**
I had to flash my comma2 for some reason and now when using the bit.ly link to the c2 package, it says an update is needed and when that update is installed, the comma2 seems to just boot loop at the recovery screen

**To Reproduce**
1. Reflash Comma2 via these steps: https://commasupport.zendesk.com/hc/en-us/articles/4413250576535-Reflashing-NEOS
2. Used the provide Comma2 link from this page to install j-vanetten open pilot.
3. Installed j-vanetten screen appears.
4. Update Required prompt appears and I click Install.
5. Downloading recovery and Downloading system bars complete.
6. Bootloop begins.

**Expected behavior**
I expected the software to install and load as it has done in the past

**Additional context**
This used to work fine but suddenly began to glitch which led me to refreshing the comma2 and thus beginning this cycle of issues.

**Comment by j-vanetten** [comment]
Closing as the C2 has it's own branch
