### ISSUE TITLE
NoPanda issue

### ISSUE THREAD

**Issue by CrazyJoeDivola** [j-vanetten/openpilot#26]
Just got my C3 this week. Tried installing from your link four different times, I always get the "NoPanda" error. Reverted to the stock open pilot after each failed attempt and it works fine. Is there a hardware change on the newest C3s that is maybe causing this issue?

**Comment by SupaTWC** [comment]
Install when the car is off, ignition off, start button status light shows off.

**Comment by j-vanetten** [comment]
Closing as there are no new comments
