### ISSUE TITLE
Downstream forks broken by forced history rewrite

### ISSUE THREAD

**Issue by Fmstrat** [j-vanetten/openpilot#37]
**Describe the bug**
The current release branch has 7 commits. At some point it's history was rewritten, which has broken any downstream forks.

**To Reproduce**
1. Fork this repo (before the rewrite)
2. Try to merge upstream after the rewrite

**Expected behavior**
When new updates to OP occur, keep the version history and rebase.

**Comment by j-vanetten** [comment]
@Fmstrat I use Comma's release tags for my development.  Sorry to say, they did the same thing to me causing me to reset my fork so I can continue to merge in their changes.
