### ISSUE TITLE
Dynamic camera offset (based on oncoming traffic) (From SA)

### ISSUE THREAD

**Issue by TheWizard1328** [j-vanetten/openpilot#4]
Saw these in another fork. Thought you might like it.
ShaneSmiskol/openpilot( https://github.com/ShaneSmiskol )

Lane Speed alerts
This feature alerts you of faster-travelling adjacent lanes and can be configured using the on-screen LS button on the bottom right to either be disabled, audible, or silent.

The idea behind this feature is since we often become very relaxed behind the wheel when being driven by openpilot, we don't always notice when we've become stuck behind a slower-moving vehicle. When either the left or right adjacent lane is moving faster than your current lane, LaneSpeed alerts the user that a faster lane is available so that they can make a lane change, overtaking the slower current lane. Thus saving time in the long run on long road trips or in general highway driving!

The original idea is thanks to Greengree#5537 on Discord. This feature is available at 35 mph and up.
-----------------------------------------------------------------
Dynamic camera offset (based on oncoming traffic)
This feature automatically adjusts your position in the lane if an adjacent lane has oncoming traffic. For example, if you're on a two-lane highway and the left adjacent lane has oncoming cars, LaneSpeed recognizes those cars and applies an offset to your CAMERA_OFFSET to move you over in the lane, keeping you farther from oncoming cars.

This feature is available from 35 to ~60 mph due to a limitation with the Toyota radar. It may not recognize oncoming traffic above 60 mph or so. To enable or disable this feature, use opEdit and change this parameter: dynamic_camera_offset.

**Comment by j-vanetten** [comment]
Yes, I do keep an eye on this fork.  I've been busy improving longitudinal control using the ACC features.  This is certainly on my radar (haha)

**Comment by TheWizard1328** [comment]
Very, very punny man.  Looking forward to trying any new features.

Wizard Worxx
Where the magic of software begins.
Robert Tauber
(780) 236-1542<tel:(780)%20236-1542>
www.Facebook.com/WizardWorxx13<http://www.Facebook.com/WizardWorxx13>

**Comment by j-vanetten** [comment]
Not going to do this.  I've decided to keep jvePilot changes limited and stay away from changing the OP model's decisions on how to drive.
